### PR TITLE
Custom nominatim server

### PR DESCRIPTION
**Pull request by srounet**
Allow one to specify a custom Nominatim server.

- adds **domain** and **scheme** parameter to Nominatim class.
- bump version to **1.8.2**
- does not break existing tests

### CODE REVIEW

**Comment by ijl** [comment]
Would it not be a little surprising if `scheme` is not respected when you specify `api`? Did you want to have the same URL for both forward and reverse geocoding? I think it may be better implemented in the same way that GoogleV3 does: https://github.com/geopy/geopy/blob/master/geopy/geocoders/googlev3.py#L42. What do you think of that `domain` implementation?

**Comment by srounet** [comment]
Didn't see the domain implementation in `GoogleV3`, I'll move my code to implement the same kind of behaviour.
As for `forward` and `reverse` geocoding, providing a unique domain resolve most of the common cases, thus, you can still create a second instance of the geocoder of your choice without specifying domain.

I think specifying domain should act like a `sandbox` where everything goes to the domain.

**Comment by ijl** [comment]
Ok. Please ping me when you add the commit so I can merge, as GitHub doesn't notify me.

**Comment by ijl** [comment]
Merged in f514de942f98bf95daeeeba27980be2cf842794f, thanks.

**Comment by ijl** [comment]
Released in 1.9.0.

**Pull request closed without merging**
