### PR TITLE
Fixed MapBox raw

### LINKED ISSUE #353: Mapbox raw attribute does not contains geocoder response for the place
For the Mapbox it would be great to have an exact API response for the place as the `raw` attribute.

I think at that line entire `feature` object needs to be used for the `place` (not just value of the `text`):
https://github.com/geopy/geopy/blob/f452d3763aab88e26f9e8b705e5cbae2dcea349b/geopy/geocoders/mapbox.py#L78

### PR DESCRIPTION
**Pull request by inoks**
Provide detailed Mapbox place API response to use as a Location `raw` attribute.

Closes #353

### CODE REVIEW

**Comment by KostyaEsmukov** [comment]
@inoks would you be able to work on this in the near future?

**Comment by zeljkobekcic** [comment]
Will this be added soon? Otherwise I would like to do that.

**Comment by inoks** [comment]
@zeljkobekcic Please do. 
Thanks!

**Comment by zeljkobekcic** [comment]
i have created the test and created a PR for @inoks fork. When he merges the PR into his fork then this PR can be merged.

**Comment by inoks** [comment]
@zeljkobekcic Thanks, I just merged!

**Comment by zeljkobekcic** [comment]
The testing fails for Python 3.4 because it can not be installed. Does anybody knows how to fix it?

This is an excerpt from the travis ci log
```
Downloading archive: https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/14.04/x86_64/python-3.4.tar.bz2
127.27s$ curl -sSf -o python-3.4.tar.bz2 ${archive_url}
curl: (7) Failed to connect to storage.googleapis.com port 443: Connection timed out
Unable to download 3.4 archive. The archive may not exist. Please consider a different version.
```

**Comment by inoks** [comment]
@zeljkobekcic I think as those changes are planned for v2, we need to create PR for the `2` branch, where tests are only for Python 3.6 and 3.7.

**Comment by KostyaEsmukov** [comment]
> I think as those changes are planned for v2, we need to create PR for the 2 branch, where tests are only for Python 3.6 and 3.7.

Given that currently `raw` might be considered completely broken, I believe it's okay to publish this in v1.

> The testing fails for Python 3.4 because it can not be installed. Does anybody knows how to fix it?

It looks like an intermittent failure. I've restarted the job, hopefully this will fix it.

**Comment by KostyaEsmukov** [comment]
The tests have passed! https://travis-ci.org/geopy/geopy/builds/534160513

I'm planning to cut a new v1 release next week with these MapBox fixes. Let me know if there's any more issues with MapBox which needs to be addressed.

**Comment by KostyaEsmukov** [comment]
`1.20.0` has been released

**Pull request merged**
